version: '2.1'

services:
  challenge-charlie:
    image: challenge-charlie
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 scripts/start.js